### ISSUE TITLE
Add type annotations and type checking

### ISSUE THREAD

**Issue by jessekrubin** [bp/resqpy#113]
Based on the setup.cfg this package is python3.7+, so there is no reason not to add type annotations.

**Comment by jessekrubin** [comment]
Hi @andy-beer

**Comment by andy-beer** [comment]
Thanks for the suggestion Jesse!

**Comment by connortann** [comment]
I don't currently think adding type hints everywhere at this stage is sufficiently value-adding to merit the extra complexity and development effort. I'm open to other opinions though.

Some advantages are:

- More robust code. Static type analysis CI tools (e.g. MyPy) could be run against type hints and may catch bugs
- Potentially easier to read explicit code, for devs familiar with type hinting

However, some disadvantages are:

- Loss of conciseness and elegance. Type hints can significantly increase the length of function definitions, and can lead to duplication of type information that is already stored in the docstrings
- Harder-to-read code. Many python devs are still not familiar with type hinting syntax and can be turned off.
- Loss of duck-typing. Python is designed around dynamic typing and inferred types, which lends a lot of flexibility. Functions which do not specify types can be used on any objects that support the relevant operators. For example, the resqpy unit conversion function `resqpy.olio.weights_and_measures.convert` will work on floats, numpy arrays, pandas series, pandas dataframes, and distributed dask arrays.

Regarding robustness, I think we have some higher priorities that would give a higher return on development effort:

1. Getting higher unit test coverage
2. Reducing duplication of code (e.g. rolling out a single base inherited class)

**Comment by connortann** [comment]
One thing we could do is gradually incorporate type hints where it makes sense to do so - for example where types are not obvious from context, or are unusual.

An existing example is `resqpy.well.add_las_to_trajectory`, which has a type hint on one argument that comes from the 3rd party lib `lasio` which might not otherwise be clear:

```python
def add_las_to_trajectory(las: lasio.LASFile, trajectory, realization=None, check_well_name=False):
```

**Comment by connortann** [comment]
I'm reminded of the post [New features planned for Python 4](https://morioh.com/p/798f2ca443ae) 

> Type-hinting has been extended to provide even fewer tangible benefits. This new and "nerfed" type hinting will be called type whispering.

:D

**Comment by jessekrubin** [comment]
Type annotations are almost always helpful; they are helpful for static analysis and helpful for anyone trying to use resqpy. Addressing type annotations for resqpy should probably come after resolving #114. 

@connortann responses to your points:

> I don't currently think adding type hints throughout the library would be sufficiently useful to merit the extra complexity and development effort. I'm open to other opinions though.

I was able to auto-generate pretty decent type annotations using monkeytype with your tests (https://pypi.org/project/pytest-monkeytype/) in a few mins. The monkeytype generated annotations are not perfect but they are a good starting place. 

> However, some disadvantages are:
> 
> * Loss of conciseness and elegance. Type hints can significantly increase the length of function definitions, and can lead to duplication of type information that is already stored in the docstrings

The current resqpy package is not concise, and my gut tells me the way resqpy's internal imports work is hiding circular imports; type annotations could be very helpful in untangling possible circular imports as well as making parts of resqpy more modular.

> * Harder-to-read code. Many (most?) python devs are still not familiar with type hinting syntax.

I think they make code easier to read. I can `gd` (go to definition) for a type on a function and know what I am working with as opposed to guessing. 

> * Loss of duck-typing. Python is designed around dynamic typing and inferred types, which lends a lot of flexibility. Functions which do not specify types can be used on any objects that support the relevant operators. For example, the resqpy unit conversion function `resqpy.olio.weights_and_measures.convert` will work on floats, numpy arrays, pandas series, pandas dataframes, and distributed dask arrays.

Type annotations and duck typing are not mutually exclusive; they work together quite nicely.

___


> I'm reminded of the post [New features planned for Python 4](https://morioh.com/p/798f2ca443ae)
> 
> > Type-hinting has been extended to provide even fewer tangible benefits. This new and "nerfed" type hinting will be called type whispering.
> 
> :D

That is a 2+ year-old article. Python-type annotations aren't going anywhere.

**Comment by connortann** [comment]
You make good points. [monkeytype](https://github.com/Instagram/MonkeyType) looks like an awesome tool - it would make it much easier to implement a first-pass set of type hints, that we could then refine. Knowing that's available as an option to get us going, I'm on board with the idea 👍 

Thanks for the input Jesse, your comments are hugely appreciated. Please keep them coming!
