### ISSUE TITLE
Adopt standard formatting of python code

### ISSUE THREAD

**Issue by jessekrubin** [bp/resqpy#114]
To make PRs easier this project should adopt some standard python formatter. I would recommend the black formatter as it is consistent and is easier on git when diffing and merging. Black pairs well with isort which sorts/organizes/formats python imports.

Link to black formatter: https://github.com/psf/black

Link to isort: https://github.com/PyCQA/isort

**Comment by connortann** [comment]
I love python black! +1 for the suggestion.

The project's [Contributing Guide](https://resqpy.readthedocs.io/en/latest/CONTRIBUTING.html#code-style) has a section on the project current's code style:

> Please try to write code according to the PEP8 Python style guide, which defines conventions such as variable naming and capitalisation. A consistent style makes it much easier for other developers to read and understand your code.
>
> Note the existing code base differs from PEP8 in using 3 spaces for indentation rather than the usual 4. When editing these modules, it is preferable that new code has indentation that is consistent with the rest of the module.

@jessekrubin, are there specific issues with the style that make PRs difficult from your perspective?

I think @andy-beer will push back rather strongly on the use of python black, as he's an ardent supporter of 3-space indentation. We've debated this one in the past, and I haven't (yet) swayed him to the 4-space clan.

**Comment by jessekrubin** [comment]
If y'all are serious about this project being open source and are serious about accepting contributions to resqpy, resqpy needs to adopt a style-guide/format. A contributor should not have to fiddle with their editor/IDE just to make a small PR to resqpy, particularly when the repo does not provide a `.editorconfig` or anything of the sort.

In part, the point of adopting black (or another formatter) is so that it can be run before commits to make diffing easier and to make code-style more consistent. Refactoring formatted code also becomes much easier.

Personally, the 3-space indentation is alarming and makes me skeptical of resqpy as a whole. If the Beer-meister (@andy-beer) cannot live without 3-spaces, you could use tabs, and then everyone could set their own tab-width in their editor.

I could even let the single line `if` statements go if the indentation were fixed.

@connortann if I were in your shoes, I would pull the trigger, which looks like it would make the most people happy. 

Another formatter you could look at is yapf: https://github.com/google/yapf

**Comment by berland** [comment]
I really support switching to black-formatting, in order to attract contribution.
