### ISSUE TITLE
Implement a resqpy RelPerm class inheriting from DataFrame

### ISSUE THREAD

**Issue by andy-beer** [bp/resqpy#155]
The existing olio.dataframe module includes a general purpose DataFrame class for storing and retrieving numerical pandas dataframe data in a RESQML object (creatively re-using the Grid2DRepresentation class and related classes).

This issue proposes implementing a specialist RelPerm class which inherits from DataFrame.

(Similarly capillary pressure data, rock compressibility etc. could have specialised resqpy classes.)

**Comment by andy-beer** [comment]
Kadija will be working on this issue – awaiting username to assign.

**Comment by kadijahassanali** [comment]
Hi Andy, I do have a git account associated with my bp credentials but I can't sign in using those. Instead, I've signed in using my personal account.
![image](https://user-images.githubusercontent.com/71336336/125848376-889c0034-6513-4df3-8a8a-743efc3f5a8a.png)

**Comment by andy-beer** [comment]
Hello Kadija,

It is strange that your bp git account is not working – we can probably get that fixed.  I think it's okay to carry on with your personal account until then.

By the way, I will be making a small change to the DataFrame init​​ arguments to accept a uuid when initialising from an existing RESQML object, and deprecating the support_root argument. This is a change we've been making to all the class initialisers.  The tutorials should be up-to-date but older material such as those presentation videos indicate use of an xml root for initialisation, which will now cause a deprecation warning.

Kind regards,
Andy.
________________________________

**Comment by andy-beer** [comment]
Sorry @berland , I meant to leave the following comment before closing your comment above:

Issue #176 has been raised to improve interoperability of the resqpy RelPerm class with equinor/pyscal.  @kadijahassanali is working on this.
