### ISSUE TITLE
Consolidate unique keys of objects to use UUID

### ISSUE THREAD

**Issue by connortann** [bp/resqpy#17]
An idea for a refactoring

Objects have a few different unique keys that are used throughout the code:

- UUID
- Part name (name of .xml file when unzipped)
- XML node

Would be good to standardise on using UUID

**Comment by andy-beer** [comment]
The main change here is for resqpy classes to accept uuid as the primary key when instantiating from existing RESQML objects (ie. from xml). Use of the xml root node arg then triggers a deprecated warning. For backward compatibility, it is preferable for the new uuid arg to come after the existing root_node (or equivalent) arg.
