### ISSUE TITLE
Improve olio.RelPerm interoperability with equinor/pyscal

### ISSUE THREAD

**Issue by andy-beer** [bp/resqpy#176]
The current olio.RelPerm.text_to_relperm_dict() function takes a filename as the argument.  This issue suggests we make a version of this function which takes a string.  This would allow easier integration (by calling code) with the equinor/pyscal library which includes methods for returning Nexus WOTABLE etc. keywords as a string.

We could also look at more efficient ways of passing rel. perm. and cap. pressure data between the two libraries, in both directions, though it is desirable not to introduce a mandatory installation dependency.

**Comment by kadijahassanali** [comment]
Hello Andy,

I've altered the function so that it can process either a text file or a string. Based on my (cursory) look at pyscal, the WaterOil (and other classes) have an add_fromtable method we could make use of. I'll let you know when I do a bit more research.

Thanks!

**Comment by kadijahassanali** [comment]
Hi @andy-beer,
I do think the add_fromtable method is sufficient to move relative permeability data from the resqpy RelPerm class to a pyscal WaterOil, GasOil or GasWater object. Please check out how I've used that method to create a pyscal WaterOil object from a Nexus .dat file.
![image](https://user-images.githubusercontent.com/71336336/129612661-2e703a89-7da1-42df-b3a3-ae124c0ec38e.png)
![water_oil_relperm_plots](https://user-images.githubusercontent.com/71336336/129612739-a7b4cb64-e559-453e-8e9f-d3b9f129e656.png)

**Comment by andy-beer** [comment]
Hello Kadija,

That is good – it looks simple enough for an application to move data from a resqpy RelPerm to a pyscal WaterOil (or similar).

Can we move from the pyscal WaterOil.table to a resqpy RelPerm (without going via Nexus syntax ascii)?  If we can't, I suggest adding an initialisation route to RelPerm to enable it – perhaps a specialised @classmethod, or working with the existing df argument to allow it to handle a pyscal format dataframe (ie. WaterOil.table), or adding a separate pyscal_df argument option to RelPerm.__init__().  Remember though that we should avoid any cross-imports between the two repositories, so calling code (like you mini-app) will be where the two meet.

I suggest that you:

  *   make an initial resqpy pull request with your code changes so far
  *   enable WaterOil.table -> RelPerm as you see fit and add it to your mini-app example
  *   create a new resqpy tutorial page showing how to move data to & fro between the two classes – basically publishing your mini-app example
  *   make one or more further pull requests for any further changes (and the tutorial)
  *   show all this to Obi & Bilal and/or present it in a Bifröst team demo session

Great work!
Andy.
________________________________

**Comment by kadijahassanali** [comment]
Hi @andy-beer,

We can move from a pyscal WaterOil.table or GasOil.table to a resqpy RelPerm object with a little reformatting of the column names as shown in the example below. I have not tried a pyscal GasWater.table which may be slightly more involved as initialization creates both WaterOil and GasOil object with dummy parameters for oil. I do think it's doable using a similar workflow.

I'll go ahead and create a tutorial page showing the two examples and touch base with Obi and Bilal.

Thanks!
Kadija
<img width="490" alt="pyscal_to_resqpy" src="https://user-images.githubusercontent.com/71336336/129928006-1fa9d688-bb66-4a63-9bad-7f5bfea541cc.PNG">

**Comment by andy-beer** [comment]
I think we have reasonable functionality here, so I'm closing the issue.
