### ISSUE TITLE
Actnum is ignored for the attached grid

### ISSUE THREAD

**Issue by mgimhof** [bp/resqpy#185]
The attached model has 64 cells, of which 4 are flagged invalid with actnum.

Yet cell_count returns 64 for both modes

```
import pytest
import resqpy.model as rq

def test_model():
    model = rq.Model('d:/dev/resqpy/tests/test_data/IJK_GRID.epc')
    grid = model.grid(uuid='a4bf7651-effe-49bc-b6fc-c6bbff9751c3')

    print(grid.cell_count(active_only=True))
    print(grid.cell_count(active_only=False))
```

[IJK_GRID.zip](https://github.com/bp/resqpy/files/7016220/IJK_GRID.zip)

**Comment by andy-beer** [comment]
I can confirm that for this model the Grid inactive attribute is not being set correctly from the actnum property, despite the property appearing to have the correct local property kind.  I will investigate further.

**Comment by andy-beer** [comment]
@mgimhof This issue arose as the active property is categorical whereas the resqpy code was expecting discrete.  The code has been changed to recognise either discrete or categorical active properties in the release tagged v1.1.3

**Comment by mgimhof** [comment]
@andy-beer

Thanks! It appears that one software application exports some unstructured grid properties as discrete, but the corresponding ijk grid properties as categorical.

**Comment by andy-beer** [comment]
@mgimhof I should have added that the new code does not try to make use of information in the associated lookup table for categorical properties – as long as the property kind is 'active', it assumes any non-zero value to indicate an active cell.
