### ISSUE TITLE
RESQPY Refactoring - Surface.py

### ISSUE THREAD

**Issue by emmanesbit** [bp/resqpy#260]
Refactoring surface.py into multiple classes, and adding further unit tests.

- [x]  Pointset
- [x]  Mesh
- [x]  Surface
- [x]  TriangulatedPatch
- [x]  CombinedSurface
- [x] BaseSurface

**Comment by andy-beer** [comment]
@emmanesbit – I saw somewhere a comment from you about the set_to_sail() method.  This is a low importance method.  It creates a Surface representing a 'sail shaped' triangle wrapped onto a spherical surface in 3D.  I used it to test the surface-grid intersection functionality with 'interesting' shaped surfaces but is unlikely to have real world application.
