### ISSUE TITLE
RESQPY Refactoring - property.py

### ISSUE THREAD

**Issue by cflynn3** [bp/resqpy#264]
Refactor property.py to make it easier to work with and increase its unit test coverage. Carry out the following steps:

- [x] Separate the existing classes in this file into multiple files.
- [x] Break down the existing functions / methods into smaller, less complex methods.
- [x] Add unit tests to test each function that has been created, including as many different code paths as possible.

**Comment by emmanesbit** [comment]
Majority complete. Creating separate issue to cover GridPropertyCollection testing and refactoring.
