### ISSUE TITLE
RESQPY Refactoring - crs.py

### ISSUE THREAD

**Issue by cflynn3** [bp/resqpy#269]
Refactor crs.py to make it easier to work with and increase its unit test coverage. Carry out the following steps:

- [ ] Break down the existing functions into smaller, less complex methods.
- [ ] Add unit tests to test each function that has been created, including as many different code paths as possible.

**Comment by andy-beer** [comment]
The crs module is quite small and simple. I suggest that code refactoring is not needed.

**Comment by cflynn3** [comment]
Agreed, although I think it is still worthwhile increasing the unit test coverage for this module.

**Comment by andy-beer** [comment]
Agreed, I'm working on some more unit testing just now.
