### ISSUE TITLE
RESQPY Testing - olio/rq_print.py

### ISSUE THREAD

**Issue by cflynn3** [bp/resqpy#271]
- [ ] Add unit tests to olio/rq_print.py.
- [ ] Add a comment / docstring saying "This code may be completely refactored with breaking changes in the future".

**Comment by andy-beer** [comment]
This module is due a complete overhaul. Some quick thoughts:

- a standardised resqpy approach to __str__, __repr__ and _repr_html_ implementations for resqpy high level classes
- some way of pre-setting a verbosity and/or keywords of interest for standard print related functions
- finally any specialist output added in rq_print style functions

**Comment by andy-beer** [comment]
rq_print has been removed from the resqpy repository
