### ISSUE TITLE
Ensure rock permeability and permeability rock are both handled

### ISSUE THREAD

**Issue by emmanesbit** [bp/resqpy#329]
In the RESQML units of measure there is one instance of a synonym, and this is it: 'rock permeability' and 'permeability rock' should be interchangeable. We might want to modify the resqpy code, which I think was generating an erroneous warning, to handle this special situation.

**Comment by andy-beer** [comment]
A change has been made which should have suppressed the warning in this situation. It could do with some manual testing then this issue can be closed.
