### ISSUE TITLE
Consistency needed in packaging

### ISSUE THREAD

**Issue by andy-beer** [bp/resqpy#366]
After the major refactoring, the top level packages, eg. strata, grid, are presenting differently. Some hide the sub packages (preferred) with full doc strings in the wrapper methods. Others put the emphasis on the sub packages. This difference shows up in readthedocs. Consistency across resqpy is needed.

**Comment by cflynn3** [comment]
For the Grid module, move the docstrings from the refactored functions to the top level class methods so that they are presented at the top level on readthedocs. Make the submodule names private to discourage their use outside the Grid class.
