### ISSUE TITLE
Timeseries extra metadata crash

### ISSUE THREAD

**Issue by maxm17** [bp/resqpy#388]
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_43768/4281837978.py in special_details(part_root)
    308 def special_details(part_root):
    309     with specials_display:
--> 310         print_node(model, part_root, detail_level = detail_toggle.index)
    311     if model is not None: model.h5_release()
    312 

/hpc/apps/bifrost/prod/x86_64/lib/live/resqpy/olio/rq_print.py in print_node(model, node, detail_level)
    763         print_EpcExternalPartReference(model, node, detail_level = detail_level)
    764     elif obj_type == 'obj_TimeSeries':
--> 765         print_TimeSeries(model, node, detail_level = detail_level)
    766     elif obj_type == 'obj_StringTableLookup':
    767         print_StringTableLookup(model, node, detail_level = detail_level)

/hpc/apps/bifrost/prod/x86_64/lib/live/resqpy/olio/rq_print.py in print_TimeSeries(model, node, detail_level)
    288     if not detail_level:
    289         return
--> 290     time_series = rts.any_time_series(model, uuid = node.attrib['uuid'])
    291     for index in range(time_series.number_of_timestamps()):
    292         if time_series.timeframe == 'geologic':

/hpc/apps/bifrost/prod/x86_64/lib/live/resqpy/time_series/_functions.py in any_time_series(parent_model, uuid)
    154     from resqpy.time_series._time_series import TimeSeries
    155 
--> 156     timeframe = timeframe_for_time_series_uuid(parent_model, uuid)
    157     if timeframe == 'human':
    158         return TimeSeries(parent_model, uuid = uuid)

/hpc/apps/bifrost/prod/x86_64/lib/live/resqpy/time_series/_functions.py in timeframe_for_time_series_uuid(model, uuid)
    138     em = rqet.load_metadata_from_xml(root)
    139     if em is not None:
--> 140         timeframe = em['timeframe']
    141         if timeframe:
    142             return timeframe

KeyError: 'timeframe'

**Comment by cflynn3** [comment]
@andy-beer Please can you set the milestone on this? If it's important I think it should be fixed as part of the initial work.
