### ISSUE TITLE
Add Example data

### ISSUE THREAD

**Issue by Duncan-Hunter** [bp/resqpy#41]
Is it possible to add some example data, or even fake data, so people who want to develop/test out the library, but don't perhaps have access to typical RESQML projects?

**Comment by andy-beer** [comment]
Thanks for this suggestion Duncan (also requested by Brennan Williams). We will add some small synthetic data sets to the repository.

**Comment by connortann** [comment]
I think we could take inspiration from seaborn, and include a simple helper method in the main `resqpy` library to make example datasets available, by just fetching from github:

https://github.com/mwaskom/seaborn/blob/e04b07eb3df135511e71e556c2bd34ef59ba08ba/seaborn/utils.py#L441

**Comment by duncan-hunter-1** [comment]
This looks like it was done with #59, as well as with the test data and tutorials so I'll close the issue
