### ISSUE TITLE
Add tutorial pages to Wiki tab

### ISSUE THREAD

**Issue by andy-beer** [bp/resqpy#43]
We have some resqpy tutorial pages on the internal bp Wiki – these can be transferred with minor edits to the Wiki tab of this github project.

**Comment by andy-beer** [comment]
@connortann Despite our discussion where we agreed to focus on readthedocs for resqpy  documentation, I've decided to port the tutorial pages to the github Wiki tab as it is so quick to do.

**Comment by connortann** [comment]
@andy-beer I think there may actually be an automated solution to convert from MediaWiki to RST, which should make this process a lot easier: https://pandoc.org/

I tested out the [online demo converter](https://pandoc.org/try/?text=&from=mediawiki&to=rst&standalone=0), it seems to work well - although the web demo has a character limit, so suggest we use the command line tool.

**Comment by connortann** [comment]
I shall post to my team to see if someone would like to get involved and help out!

**Comment by duncan-hunter-1** [comment]
i can try picking this up - any tips on getting clean html data from wiki pages?

**Comment by connortann** [comment]
On Wiki pages, try clicking "edit" and then use the plaintext editor. This will enable to you grab nice and clean wikimarkup.

**Comment by duncan-hunter-1** [comment]
See merged #51
