### ISSUE TITLE
Unexpected output of resqpy.crs.Crs.is_right_handed_xyz()

### ISSUE THREAD

**Issue by nadukandi** [bp/resqpy#519]
Kindly help me understand this output (I have read an EPC file and I am doing quieres on the coordinate reference system object):

> In [2]: crs.is_right_handed_xyz()
> Out[2]: False
> 
> In [3]: (crs.axis_order in ["northing easting", "southing westing", "westing northing"]) == crs.z_inc_down
> Out[3]: True
> 
> In [4]: crs.z_inc_down
> Out[4]: False
> 
> In [5]: crs.axis_order
> Out[5]: 'easting northing'

The outputs of the first two commands are different. Is it a bug (I glanced at the code and I don't see any) or am I doing something wrong?

**Comment by andy-beer** [comment]
Please try your code again using an updated pull from the master branch (or installing version v2.3.5 or later).

If this does not fix the issue we might need to look together in detail at your code and/or data, as I was unable to replicate the issue.

Kind regards, Andy.

**Comment by nadukandi** [comment]
Thanks @andy-beer ! I had an older version (`1.51.2`) of `resqpy`. Updating it to version `2.3.5` solved the problem. 
> (toptenv) ? python -m pip show resqpy                                  
> Name: resqpy                                                           
> Version: 2.3.5                                                         
> Summary: Python API for working with RESQML models                     
> Home-page: https://github.com/bp/resqpy                                
> Author: BP                                                             
> ...                                                           

> In [2]: crs.axis_order, crs.z_inc_down
> Out[2]: ('easting northing', False)
> 
> In [3]: crs.is_right_handed_xyz()
> Out[3]: True
> 
> In [4]: (crs.axis_order in ["northing easting", "southing westing", "westing northing"]) == crs.z_inc_down
> Out[4]: True
