### ISSUE TITLE
Consolidate & refactor resqpy.organize classes

### ISSUE THREAD

**Issue by connortann** [bp/resqpy#75]
Refactor and add tests to classes in organize.py , to achieve:

- Common inherited basic methods (e.g. repr, ipython)
- Instantiating from UUID, with backward compatibility for root_node (supporting #17)
- Reduce duplication of code

Classes checklist:
- [x] OrganizationFeature
- [x] GeobodyFeature
- [x] BoundaryFeature
- [x] FrontierFeature
- [x] GeologicUnitFeature
- [x] FluidBoundaryFeature
- [x] RockFluidUnitFeature
- [x] TectonicBoundaryFeature
- [x] GeneticBoundaryFeature
- [x] WellboreFeature
- [x] FaultInterpretation
- [x] EarthModelInterpretation
- [x] HorizonInterpretation
- [x] GeobodyBoundaryInterpretation
- [x] GeobodyInterpretation
- [x] WellboreInterpretation

**Comment by andy-beer** [comment]
Pull request #77 makes the changes for the remaining classes in organize.py, as well as introducing the reuse functionality.
