### ISSUE TITLE
StringLookup, TimeSeries and Crs to use BaseResqpy and reuse functionality

### ISSUE THREAD

**Issue by andy-beer** [bp/resqpy#79]
This issue is to modernise the resqpy StringLookup and TimeSeries classes to inherit from BaseResqpy; and also to add the reuse argument to their create_xml() methods.

The Crs class already has reuse; however, it is to be modified to inherit from BaseResqpy

**Comment by connortann** [comment]
May I suggest taking this opportunity to add in some simple tests for the `TimeSeries` & `StringLookup` classes, and the `condolidation` functions?
