### ISSUE TITLE
Error when adding a constant value boolean DiscreteProperty to a PropertyCollection

### ISSUE THREAD

**Issue by emmanesbit** [bp/resqpy#810]
When adding a boolean DiscreteProperty to a property collection with the value True or False, I run into an error where the code is trying to find the min/max of a boolean from the xml. This issue can be avoided by using 1/0 as the constant value, but this is not ideal

Further traceback on the error to be added shortly

**Comment by andy-beer** [comment]
Resolved by pull request #816
