### ISSUE TITLE
write_wellspec does not use a property for the STAT column

### ISSUE THREAD

**Issue by emmanesbit** [bp/resqpy#813]
Currently the write_wellspec method appears to generate the STAT column as either 'all on' or 'all off', depending on the user provided arguments. Where there is a property on the blocked well relating to well status (in specific cells in particular) it would be useful to be able to provide the UUID to this property, and use this for the STAT column instead of a bulk value

**Comment by andy-beer** [comment]
Resolved by merge request #817
